import Footer from "@components/Footer"
import Navbar from "@components/Navbar"
import styles from '@styles/scss/_Course.module.scss'
import Head from "next/head"

const courseData = [
    {
        title: '化學實驗室',
        detail: '讓我們一起探索元宇宙化學實驗室！在這裡，您將體驗線上虛擬實驗，挑戰科學的極限。加入我們，與全球化學愛好者共同學習、互動及創新。立即踏上獨特的化學冒險，揭開科學奧秘的神秘面紗！',
        imgId: 'course1',
    },
    {
        title: '魔幻哈哈鏡',
        detail: '歡迎來到哈哈鏡的奇幻世界！你會發現這裡的世界都有點不尋常，藉由曲面鏡的不規則光線反射與聚焦，無論是想變成個超級瘦長的巨人或是可愛短短胖胖的樣子，在這裡都能實現！',
        imgId: 'course2',
    },
    {
        title: '身體地圖室',
        detail: '數位人體地圖利用沉浸式體驗的教學軟體，提供人體模型、肌肉組織、骨骼架構等，搭配上元宇宙系統，使學生與老師可以有多種互動方式，提供更有趣的多元教學工具。',
        imgId: 'course3',
    },
    {
        title: '宇宙間只有我們嗎',
        detail: '為什麼太陽總是東升西落？星星的真實樣貌長怎樣？現在跟我們搭上太空艙，觀察星體的運動軌跡，連光也無法逃離的黑洞引力，揭開浩瀚宇宙的神秘面紗！',
        imgId: 'course4',
    },
    {
        title: '給我一個支點 我能舉起地球',
        detail: '這聽起來有些誇張，但你知道日常生活中的剪刀、開瓶器、筷子都是用一樣的原理嗎？想學習更多省力密技？快來看看吧',
        imgId: 'course5',
    },
    {
        title: '重拾信心，從Zero到Shero',
        detail: '無論是開啟輻射醫學大門的瑪麗·居禮 ，還是計算阿波羅登月計畫中至關重要的軌道參數的凱薩琳．強森，女性在科學領域上皆有優秀表現。透過傑出女科學家的故事，打破性別框架，成為勇敢追求自己選擇的Shero!',
        imgId: 'course6',
    },
]
export default function Course() {
    return (
        <>
            <Head>
                <title>STEMeta&GeEco - 沉浸式遊戲化課程介紹</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <section className={styles.container}>
                <h1>沉浸式遊戲化課程介紹</h1>
                <div className={styles.wrap}>
                    {courseData.map((data, index) =>
                        <div className={styles.item} key={index}>
                            <div className={styles.content}>
                                <span>課程{index + 1}</span>
                                <h2>{data.title}</h2>
                                <p>{data.detail}</p>
                            </div>
                            <div className={`${styles.cousreImg} ${styles[data.imgId]}`}>
                                <img src={`/images/${data.imgId}.png`} alt="1" />
                            </div>
                        </div>
                    )}
                </div>
            </section>
            <Footer />
        </>
    )
}